### ISSUE TITLE
Library does not log extra exception detail for Console Logger

### ISSUE THREAD

**Issue by eloisetaylor5693** [RehanSaeed/Serilog.Exceptions#86]
When using this setup, the extra exception properties are not output

```
private static readonly ILogger Logger = new LoggerConfiguration()
            .Enrich.WithExceptionDetails()
            .WriteTo.Console()
            .CreateLogger();
```

**Comment by eloisetaylor5693** [comment]
Simple example:
```

using Serilog;
using Serilog.Exceptions;
using System;

namespace SerilogExceptionsLibUsingConsoleLogger
{
    public static class Program
    {
        private static readonly ILogger Logger = new LoggerConfiguration()
            .Enrich.WithExceptionDetails()
            .WriteTo.Console()
            .CreateLogger();

        public static void Main()
        {
            try
            {
                ThrowAnException();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "An error occurred");
            }
            finally
            {
                Console.ReadLine();
            }
        }

        private static void ThrowAnException()
        {
            var exception = new Exception("An exception message.");
            exception.Data.Add("someData", "This is some exception data");

            throw exception;
        }
    }
}
```

With packages:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Serilog" version="2.7.1" targetFramework="net461" />
  <package id="Serilog.Exceptions" version="4.1.0" targetFramework="net461" />
  <package id="Serilog.Sinks.Console" version="3.1.1" targetFramework="net461" />
</packages>
```


Gives this output:
```
[15:10:10 ERR] An error occurred
System.Exception: An exception message.
   at SerilogExceptionsLibUsingConsoleLogger.Program.ThrowAnException() in C:\Code\SerilogExceptionsLibUsingConsoleLogger\SerilogExceptionsLibUsingConsoleLogger\Program.cs:line 35
   at SerilogExceptionsLibUsingConsoleLogger.Program.Main() in C:\Code\SerilogExceptionsLibUsingConsoleLogger\SerilogExceptionsLibUsingConsoleLogger\Program.cs:line 18
```


But I would have expected to see more exception detail than exception.ToString() gives.  For example I would expect to see the data properties in the logged error, based on the documentation for this library.

**Comment by krajek** [comment]
Hi @eloisetaylor5693 , thanks for reaching out to us.

`Serilog.Sinks.Console` sink's default output template does not display enriched properties at all. Not for `Serilog.Exceptions` and not for any other (like standard `Enrich.FromLogContext()` or `Enrich.WithProperty`).

If you need want that you need to specify custom template including `Properties` like that:

```
.WriteTo.Console(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception} {Properties:j}")
```

Then your output will look like that:

```
2018-12-17 07:30:13.045 +01:00 [ERR] An error occurred
System.Exception: An exception message.
   at SerilogExceptionsLibUsingConsoleLogger.Program.ThrowAnException() in C:\Users\krajewa1\source\repos\ConsoleExceptions\ConsoleExceptions\Program.cs:line 40
   at SerilogExceptionsLibUsingConsoleLogger.Program.Main() in C:\Users\krajewa1\source\repos\ConsoleExceptions\ConsoleExceptions\Program.cs:line 22
 {"PROP": "VALUE", "ExceptionDetail": {"Type": "System.Exception", "Data": {"someData": "This is some exception data"}, "HResult": -2146233088, "Message": "An exception message.", "Source": "ConsoleExceptions"}}
```

What's more, many other sinks are the same.  On the other hand, I think that you got a point, that we could be explicit about it in the docs. I will add some guidance regarding the topic.

Hope that helps.

**Comment by krajek** [comment]
I have extended the `README.md` with short description and an example in 84b62d1.
That should help, thanks again @eloisetaylor5693 .
